export const PrimaryColor = '#FFFFFF'
export const SecondaryColor = '#292929'
export const TertiaryColor = '#909090'
export const QuaternaryColor = '#292929'
export const QuinaryColor = '#FFFFFF'
export const BackgroundColor = '#F5F5F5'
export const LightColor = '#909090'